version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - aws s3 cp s3://ghost-secrets/gatsby.ghost.json .ghost.json
      - npm install -g gatsby-cli
  build:
    commands:
      - npm install
      - gatsby build
artifacts:
  files:
    - 'public/*'
